parameters:
    # ... other parameters
    security.acl.permission.map.class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap

services:
    app.admin.product:
        class: AppBundle\Admin\ProductAdmin
        arguments: [~, AppBundle\Entity\Product, 'PixSortableBehaviorBundle:SortableAdmin']
        tags:
            - {name: sonata.admin, manager_type: orm, group: Контент, label: Оборудование}
        calls:
             - [ setPositionService, [@pix_sortable_behavior.position]]

    app.admin.product_has_media:
        class: AppBundle\Admin\ProductHasMediaAdmin
        arguments: [~, AppBundle\Entity\ProductHasMedia, AppBundle:ProductHasMediaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Контент, label: Изображения оборудования, show_in_dashboard: false}

    app.admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, 'PixSortableBehaviorBundle:SortableAdmin']
        tags:
            - {name: sonata.admin, manager_type: orm, group: Контент, label: Категории}
        calls:
             - [ setPositionService, [@pix_sortable_behavior.position]]

    app.admin.mark:
        class: AppBundle\Admin\MarkAdmin
        arguments: [~, AppBundle\Entity\Mark, 'PixSortableBehaviorBundle:SortableAdmin']
        tags:
            - {name: sonata.admin, manager_type: orm, group: Контент, label: Бренды}
        calls:
             - [ setPositionService, [@pix_sortable_behavior.position]]
